elasticsearch:
  image: elasticsearch
  volumes:
    - /opt/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
    - 9300:9300
  container_name: elasticsearch

kibana:
  image: kibana
  links:
    - elasticsearch:elasticsearch
  ports:
    - 5601:5601
  container_name: kibana
